services:
  emulator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    devices:
      - /dev/kvm
    ports:
      - "5555:5555"
      - "5554:5554"
    volumes:
      - avd-data:/data
    environment:
      - EMULATOR_RAM=1536
      - AVD_NAME=rooted33
    stdin_open: true
    tty: true

volumes:
  avd-data: